import { TSiteConfig } from "@/types";

export const siteData: TSiteConfig = {
	name: "jmarcosg",
	description:
		"Juan Marcos is a Frontend/Fullstack Software Developer building scalable web applications and integrating applied AI.",
	links: {
		mail: "jmarcos.gonzalez94@gmail.com",
		linkedin: "https://linkedin.com/jmarcosg",
		github: "https://github.com/jmarcosg",
	},
	languages: ["Spanish (native)", "English (C1)"],
	softSkills: [
		"Communication",
		"Proactivity",
		"Team-working",
		"Adaptability",
		"Creativity",
		"Growth Mindset",
		"Mentoring",
	],
	frontend: [
		"React",
		"NextJS",
		"Angular",
		"TypeScript",
		"ShadcnUI",
		"Tailwind CSS",
		"Material UI",
		"Bootstrap",
	],
	backend: [
		"Node.js",
		"Express",
		"NestJS",
		"PHP",
		"Laravel",
		"REST APIs",
		"Medusa",
		"Supabase",
		"Strapi",
		"Clerk",
		"SQL",
		"MySQL",
		"PostgreSQL",
		"MongoDB",
	],
	appliedAI: [
		"LLMs",
		"Conversational AI",
		"Automated Product Classification",
		"CSV/Excel Processing",
	],
	cloudTools: [
		"DigitalOcean",
		"Git",
		"Agile Methodologies",
		"Technical Documentation",
	],
	mobile: ["React Native", "Ionic"],
	experience: [
		{
			title: "Frontend Software Developer",
			company: "Minimalart",
			link: "https://minimalart.co/",
			location: "Buenos Aires, Argentina (Remote)",
			startDate: "2025",
			endDate: "Present",
			description: [
				"Developed and optimized websites for brands such as Arcor, Coca-Cola, Issue, Saphirus, Villeneuve, and Fontagro using React, Next.js, and Tailwind CSS.",
				"Built modern, responsive, and maintainable interfaces focused on performance, scalability, and user experience.",
				"Developed, deployed, and maintained backend services and integrations with Node.js, Medusa, Supabase, Strapi, Clerk, and DigitalOcean.",
				"Contributed to key products including Arcor en Casa Chile, the full redesign of Issue Color, and AI-powered tools for Selectio.",
				"Implemented AI-powered solutions: a natural-language chat to search products, filter categories, and add items to cart; and an automated cataloging tool that infers product categories and enhances titles and descriptions from product images.",
			],
			tags: [
				"Software Development",
				"E-commerce",
				"Medusa",
				"AI Integration",
				"Collaboration",
			],
		},
		{
			title: "Teaching Assistant",
			company: "Universidad Nacional del Comahue",
			link: "https://www.fi.uncoma.edu.ar/",
			location: "Neuquén, Argentina (Hybrid)",
			startDate: "2023",
			endDate: "Present",
			description: [
				"Supported Introduction to Object-Oriented Programming and Dynamic Web Programming courses, reinforcing OOP, PHP, web security practices, libraries, and database persistence.",
				"Reviewed practical assignments, answered student questions, and guided exercises to strengthen programming fundamentals, object-oriented design, and maintainable web development.",
			],
			tags: ["Teaching", "Mentoring", "OOP", "Web Security"],
		},
		{
			title: "Fullstack Software Developer",
			company: "Secretaría de Modernización - Municipalidad de Neuquén",
			link: "https://www.neuquencapital.gov.ar/secretaria-de-modernizacion/subsecretaria-de-sistemas/",
			location: "Neuquén, NQN, Argentina",
			startDate: "2022",
			endDate: "2025",
			description: [
				"Designed, developed, and implemented scalable software applications using React, Angular, TypeScript, Laravel, PHP, and SQL.",
				"Improved user experience and performance across municipal systems, increasing user interaction by 30% and reducing page load times by 50%.",
				"Led technical development of responsive and maintainable solutions for internal processes and citizen-facing digital services.",
			],
			tags: [
				"Software Development",
				"Web Applications",
				"Angular",
				"Laravel",
				"Collaboration",
			],
		},
		{
			title: "Fullstack Software Developer",
			company: "Universidad Nacional del Comahue",
			link: "https://www.fi.uncoma.edu.ar/",
			location: "Neuquén, NQN, Argentina",
			startDate: "2020",
			endDate: "2022",
			description: [
				"Developed an application to help people with Autism Spectrum Disorder learn JavaScript programming using React, Node.js, MongoDB, and Google Blockly.",
				"Led the redesign and refactoring of the university events platform Juntar to improve scalability, performance, and UX using Laravel, Tailwind CSS, MySQL, Livewire, and Jetstream.",
				"Collaborated on the Gukena electronic voting system with the Euclides development team using SIU-TOBA, PHP, Bootstrap, and PostgreSQL.",
			],
			tags: [
				"Software Development",
				"React",
				"Laravel",
				"Web Applications",
				"Collaboration",
			],
		},
	],
	education: [
		{
			school: "Universidad Nacional del Comahue",
			location: "Neuquén, NQN, Argentina",
			link: "https://www.fi.uncoma.edu.ar/",
			degree: "Bachelor's Degree",
			fieldOfStudy: "Computer Science",
			description:
				"Learning about algorithms, data structures and software engineering.",
			startDate: "2023",
			endDate: "Present",
		},
		{
			school: "Universidad Nacional del Comahue",
			location: "Neuquén, NQN, Argentina",
			link: "https://www.fi.uncoma.edu.ar/",
			degree: "University Technician",
			fieldOfStudy: "Web Application Development",
			description:
				"Learnt about algorithms, UX/UI and web development. Graduated with GPA: 9.0/10.0.",
			startDate: "2020",
			endDate: "2023",
		},
	],
};
